name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-response:
    # Only run if the comment contains @claude or if it's a PR
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configure Claude's behavior
          model: claude-3-5-sonnet-20241022
          
          # Custom instructions for your project
          custom_instructions: |
            This is a React/Next.js project for UI component generation called UIGen.
            Key technologies: Next.js 15, React 19, TypeScript, Tailwind CSS v4, Prisma with SQLite.
            
            The app uses a virtual file system to generate components with AI assistance.
            All generated components should follow the creative styling guidelines in the generation prompt.
            
            When creating components:
            - Use distinctive color palettes (avoid generic blue/gray)
            - Implement creative animations and micro-interactions
            - Focus on modern, engaging designs with personality
            - Ensure mobile responsiveness
            - Follow the existing code patterns and conventions